name: Build & Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:    
      - '*'

env:
  ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

jobs:

  build-mmkv-kotlin:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build All
        run: ./gradlew :mmkv-kotlin:assemble
        
      - name: Run Native Tests
          run: ./gradlew :mmkv-kotlin:macosX64Test --stacktrace

      - name: Run Android Instrumentation Tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: [23, 31, 33]
            target: [default]
            arch: x86_64
            profile: Nexus 6
            script: ./gradlew :mmkv-kotlin:connectedDebugAndroidTest --stacktrace
