name: Build & Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:    
      - '*'

jobs:

  build-mmkv-kotlin:
    runs-on: macos-15-intel
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
    
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache Build Tooling
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
        
      - name: Build All
        run: pod repo update --verbose && ./gradlew :mmkv-kotlin:assemble
        
      - name: Run Native Tests
        run: ./gradlew :mmkv-kotlin:cleanMacosX64Test && ./gradlew :mmkv-kotlin:macosX64Test --stacktrace

      - name: AVD Cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-36

      - name: Create AVD and Generate Snapshot for Caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          profile: pixel_6
          emulator-build: 14257411
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android 16 Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          profile: pixel_6
          emulator-build: 14257411
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :mmkv-kotlin:connectedDebugAndroidTest --stacktrace

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: mmkv-kotlin/build/reports
        if: failure()
