name: Build & Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:    
      - '*'

jobs:

  build-mmkv-kotlin:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build All
        run: ./gradlew :mmkv-kotlin:assemble
        env:
          ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.signingKeyId }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
        
      - name: Run Test
        run: ./gradlew macosX64Test --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.signingKeyId }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
